### ISSUE TITLE
Highlight self

### ISSUE THREAD

**Issue by Olivia5k** [hdima/python-syntax#21]
`self` is the standard keyword for self-reference in Python OO. I suggest that we link it to `special`.

I tried to find prior discussion about this since I felt that this kinda had to be discussed before, but I found nothing. Apologies if that was the case!

**Comment by hdima** [comment]
Probably not so good example but there's a class which uses `s` instead of `self`: https://hg.python.org/cpython/file/3.4/Lib/sched.py#l45

> I'll respect your decision, but I'll also express some general concern about the Open Source way of disregarding useful ideas and changes because they might be troublesome for a single hypothetical power user.

I think the main point of Open Source is that you can create your own version of a project if you think that your changes are useful and they can't be incorporated to the mainline version for some reason. It's actually one of the reasons why this project exists.
